### ISSUE TITLE
Song API methods not documented in ReadMe

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#24]
I found some undocumented methods in song.py and tested them. They work, but are not in the ReadMe.

jump_by (float)
jump_to_prev_cue
jump_to_next_cue
duplicate_scene (int)
duplicate_track (int)
tap_tempo
trigger_session_record

I also found the property start_time in song.py, but this does not work and seems to be a clip - not song - property.

**Comment by ideoforms** [comment]
Done

**Comment by Coupe70** [comment]
I still see start_time in song.py (line 60).
Doesn't do any harm, but I think it does not belong in song.py

![grafik](https://user-images.githubusercontent.com/70244400/208316754-652ea911-de93-4367-8c7b-c89ad0c198d2.png)
