### ISSUE TITLE
Track API properties not documented in ReadMe

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#29]
**/live/track/get/clips/color** 

get&set
arm, color_index, current_monitoring_state, fold_state

are working, but missing in ReadMe
Seems all the above track properties and more also have undocumented listeners (only color, name, arm tested).

Are there undocumented listeners for clips implemented already, too?
I'm not able to "find" listeners in track.py, so I don't know what to look for in clip.py.

**Comment by ideoforms** [comment]
Done

**Comment by Coupe70** [comment]
/live/track/get/clips/color still missing in ReadMe (Track: Properties of multiple clips).
